// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abnbkjlwkcxzfrsignpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFibmJramx3a2N4emZyc2lnbnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzUxNDYsImV4cCI6MjA2NTMxMTE0Nn0.zzgzLTqoRTfKrw7OHeOpWmhnoB3ChBhRjmSACSwEYfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);